### ISSUE TITLE
Stereotypes vanish if arrow is to small

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Apollon#101]
#### To Reproduce

1. Draw an include relationship
2. move one usecase towards the other until the stereotype vanishes

#### Expected behavior
It is stated somewhere what kind of relation this is. If you are provided with a non editable diagram (e.g. in an assessing situation) you can't move the usecase in order to see the stereotype.

#### Screenshots
Working:
[![Screenshot from Gyazo](https://gyazo.com/f22b0fe5debecb7c356846d4e54c58f3/raw)](https://gyazo.com/f22b0fe5debecb7c356846d4e54c58f3)

Not anymore:
[![Screenshot from Gyazo](https://gyazo.com/ff6a0bface2fb9e142b5cd852a615492/raw)](https://gyazo.com/ff6a0bface2fb9e142b5cd852a615492)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome v81.0.4044.138
</pre></details>

**Comment by TobiasPr** [comment]
There are many approaches, how we could solve this issue:

1. If it's about the assessment, then we could include the element type in the assessment dialog.
![image](https://user-images.githubusercontent.com/22955066/82537806-ee880c00-9b4a-11ea-9b7e-05b36b2f9e29.png)
2. If you want to see it already in the diagram, we can make the text not disappear, which will lead to a bad visual result
![image](https://user-images.githubusercontent.com/22955066/82537064-bdf3a280-9b49-11ea-81a8-58cb24bd1875.png)
3. We can limit the user capability to connect and move elements (elements have a min distance, everything below, will not be accepted)

I don't think the third option is not a good solution, because it could lead to confusion in how to use the editor. Which way would you prefer option 1 or option 2?

**Comment by julian-christl** [comment]
I'd say the first option. Overlapping is not that nice to look at...

**Comment by TobiasPr** [comment]
@julian-christl will be included in the next release, which is planned for the 26.05.2020

**Comment by TobiasPr** [comment]
Okay, I did a small change, see screenshot. The Element type is now part of the Assessment Dialog Popup. The header follows the schema: Assessment for _ElementType_ "_ElementName_"
I also changed the tranlsations so that we can determine the translation for the element type, which is more readable
![image](https://user-images.githubusercontent.com/22955066/82560531-ea231980-9b71-11ea-876f-3b2d094348a4.png)

**Comment by julian-christl** [comment]
Wonderful, thank you. This looks great.
